dist: trusty
language: node_js
node_js: "8"
sudo: required

matrix:
  fast_finish: true
  include:
    - node_js: "8"
      language: node_js
      env: TEST=WASM
      services: docker

    - language: c++
      env: TEST=CPP
      services: docker

    - python: "3.6"
      language: python
      env: TEST=PYTHON
      cache: pip
      services: docker

    - python: "3.6"
      language: python
      env: TEST=PYTHON_TABLE
      cache: pip
      services: docker

    - python: "3.6"
      language: python
      env: TEST=PYTHON_NODE
      cache: pip
      services: docker

    - language: c++
      env: TEST=CPP_OSX
      os: osx

  allow_failures:
    - language: c++
      env: TEST=CPP_OSX
      os: osx

env:
  global:
    - EM_USE_GLOBAL_CACHE=1

install:
  - if [ "$TEST" = "CPP_OSX" ]; then brew install yarn; fi
  - if [ "$TEST" = "PYTHON_NODE"]; then curl -sL https://deb.nodesource.com/setup_8.x | bash - && apt-get install npm; fi
  - yarn

script:
  - if [ "$TEST" = "WASM" ]; then PSP_DOCKER=1 yarn lint; fi
  - if [ "$TEST" = "WASM" ]; then PSP_DOCKER=1 yarn build; fi
  - if [ "$TEST" = "WASM" ]; then PSP_DOCKER=1 yarn test --quiet; fi
  - if [ "$TEST" = "CPP" ]; then PSP_DOCKER=1 yarn build_cpp; fi
  - if [ "$TEST" = "CPP" ]; then PSP_DOCKER=1 yarn test_cpp; fi
  - if [ "$TEST" = "PYTHON" ]; then PSP_DOCKER=1 yarn ci_python; fi
  - if [ "$TEST" = "PYTHON_TABLE" ]; then PSP_DOCKER=1 yarn ci_python:table; fi
  - if [ "$TEST" = "PYTHON_NODE" ]; then PSP_DOCKER=1 yarn ci_python:node; fi
  - if [ "$TEST" = "CPP_OSX" ]; then yarn build_cpp; fi
  - if [ "$TEST" = "CPP_OSX" ]; then yarn test_cpp; fi
