dist: trusty

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules
    - packages/perspective/obj
    - packages/perspective/node_modules
    - packages/perspective-examples/node_modules
    - packages/perspective-jupyterlab/node_modules
    - packages/perspective-viewer/node_modules
    - packages/perspective-viewer-highcharts/node_modules
    - packages/perspective-viewer-hypergrid/node_modules

env:
  global:
    - EM_USE_GLOBAL_CACHE=1

sudo: required

services:
  - docker

install:
  - npm install

jobs:
  include:
    - stage: Build
      script: PSP_DOCKER=1 npm run build
    - stage: Test
      script: PSP_DOCKER=1 npm run test:build
    - stage: Test
      script: PSP_DOCKER=1 npm run test:run
    - stage: Test
      script: npm run test:run_quiet
