[package]
name = "perspective-bundle"
version = "2.1.1"
edition = "2021"

[[bin]]
name = "bundle"
path = "main.rs"
bench = false

[dependencies]
flate2 = "1.0.20"
wasm-bindgen-cli-support = "0.2.84"
wasm-opt = "0.112.0"
