[package]
name = "perspective-viewer"
version = "1.0.8"
authors = ["Andrew Stein <steinlink@gmail.com>"]
edition = "2021"
description = "A frontend for Perspective"
repository = "https://github.com/finos/perspective"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/rust/lib.rs"

[features]
define_custom_elements_async = []
default = []

[dependencies]
# Provides async `Mutex` for locked sections such as `render`
async-std = "1.9.0"

# Allow async methods to be used in traits
async-trait = "^0.1.52"

# Encode persistence tokens
base64 = "0.13.0"

# Timezone correction
chrono = "0.4"

# More derivable traits
derivative = "2.2.0"

# Easy way to define & implement a singleton trait (type extension)
extend = "1.1.2"

# Compress tokens
flate2 = "1.0.20"

# General async tools
futures = "0.3.12"

# General iterator improvements
itertools = "0.10.1"

# Performance improvements for common string to JS conversions
js-intern = "0.3.1"

# Comma-sep numeric representation
num-format = "0.4.0"

# MessagePack serialization
rmp-serde = "0.15.5"

# Serialization for tokens and JS APIs
serde = { version = "1.0", features = ["derive"] }

# Support for "unknown"/dicitonary types such as `plugin_config`
serde_json = { version = "1.0.59", features = ["raw_value"] }

# Browser API bindings
wasm-bindgen = { version = "=0.2.80", features = ["serde-serialize"] }

# Browser `Promise` bindings
wasm-bindgen-futures = "0.4.20"

# https://github.com/yewstack/yew/issues/2154
yew = { git = "https://github.com/yewstack/yew", rev = "3760c5f8b56a8ac1730356f4ddbbdc949b9f120c", features = ["csr"] }

[dependencies.web-sys]
version = "0.3.57"
features = [
    # "Performance",
    "Blob",
    "Clipboard",
    "CssStyleDeclaration", 
    "CssStyleSheet",
    "CssRuleList",
    "CssRule",
    "CssStyleRule",
    "CustomEvent",
    "CustomEventInit",
    "DataTransfer",
    "Document",
    "DomRect",
    "DomStringMap",
    "DomTokenList",
    "Element",
    # "DomTokenList",
    "Event",
    "EventTarget",
    "EventListener",
    "FontFace",
    "FontFaceSet",
    "FontFaceSetIterator",
    "FontFaceSetIteratorResult",
    # "DocumentFragment",
    "HtmlCollection",
    "HtmlElement",
    "HtmlTextAreaElement",
    "HtmlSelectElement",
    "InputEvent",
    "KeyboardEvent",
    # "MouseEvent",
    "MutationObserver",
    "MutationObserverInit",
    "MutationRecord",
    "Navigator",
    "Node",
    "NodeList",
    'Performance', 
    # "TouchEvent",
    # "TouchList",
    # "Touch",
    # "WheelEvent",
    "ReadableStreamDefaultReader",
    "ShadowRoot",
    "ShadowRootMode",
    "ShadowRootInit",
    "StyleSheet",
    "StyleSheetList",
    "Url",
    "VisibilityState",
    "Window"
]


[dependencies.js-sys]
version = "0.3"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.dev]
panic = "abort"
opt-level = "s"

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = true
strip = true