[alias]
bundle = "run -p perspective-bundle"

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]
target-dir = "rust/target"

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
rustflags = [
    "--cfg=web_sys_unstable_apis",
    "-Ctarget-feature=+bulk-memory,+simd128",
]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "--cfg=web_sys_unstable_apis"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "--cfg=web_sys_unstable_apis"]

[future-incompat-report]
frequency = 'never'

[unstable]
bindeps = true
package-workspace = true

[term]
quiet = false
verbose = false
color = 'always'
