[alias]
bundle = "run -p perspective-bundle"

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]
target-dir = "rust/target"

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
rustflags = [
    "--cfg=web_sys_unstable_apis",
    "-Ctarget-feature=+bulk-memory,+simd128,+relaxed-simd",
]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "--cfg=web_sys_unstable_apis"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "--cfg=web_sys_unstable_apis"]

[future-incompat-report]
frequency = 'never'

# TODO this is required to synth public releases on GH Actions
[patch.crates-io]
perspective-client = { path = "rust/perspective-client" }
perspective-server = { path = "rust/perspective-server" }
perspective-js = { path = "rust/perspective-js" }
perspective-python = { path = "rust/perspective-python" }
perspective-viewer = { path = "rust/perspective-viewer" }
perspective = { path = "rust/perspective" }

[unstable]
bindeps = true
package-workspace = true

[term]
quiet = false
verbose = false
color = 'always'
