[alias]
bundle = "run -p perspective-bundle --"

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'

[future-incompat-report]
frequency = 'never'
